### ISSUE TITLE
Undef float returned if no intersection?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#1]
https://github.com/DavisThuillier/Ludwig.jl/blob/983ea415143ce77f9859ec0f940c28f5f52eb831/src/integration.jl#L47

If there is no intersection between the sphere and the plane for any band, the for loop finishes without assigning integral and it seems the function returns an undef float instead of zero?

**Comment by thomasscaffidi** [comment]
Same here: https://github.com/DavisThuillier/Ludwig.jl/blob/983ea415143ce77f9859ec0f940c28f5f52eb831/src/integration.jl#L162

**Comment by DavisThuillier** [comment]
Old version of function scrubbed from integration.jl
