### ISSUE TITLE
symmetrize function does not work for electron-impurity matrix (the factors of fermi dirac distributions should not be there), but seems to still be used when loading the electron-impurity matrix

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#10]
https://github.com/DavisThuillier/Ludwig.jl/blob/ae410e2cd2960b22efeb5ac8ca592a9f3aa514e0/scripts/Sr2RuO4_analysis.jl#L29

There should be no need to symmetrize for the electron-impurity scattering anyway

**Comment by thomasscaffidi** [comment]
I think this might be the cause for the weird dependence on Vimp?

**Comment by DavisThuillier** [comment]
Because of the small value of Vimp, this error only results in a < 0.01% change in the viscosities.
