### ISSUE TITLE
\delta = 0.5 hardcoded here

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#11]
https://github.com/DavisThuillier/Ludwig.jl/blob/ae410e2cd2960b22efeb5ac8ca592a9f3aa514e0/scripts/Sr2RuO4_analysis.jl#L116

**Comment by DavisThuillier** [comment]
This was the hardcoded \delta problem that gave us the plot before. Since corrected locally.
