### ISSUE TITLE
The sum should exclude the diagonal term

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#12]
https://github.com/DavisThuillier/Ludwig.jl/blob/ae410e2cd2960b22efeb5ac8ca592a9f3aa514e0/scripts/Sr2RuO4_analysis.jl#L33

This formula is only ok if L[i,i] is initially zero, but this is not guaranteed: for electron_electron, as far as I can tell it looks like L[i,i] gets calculated and assigned

**Comment by DavisThuillier** [comment]
I disagree here. If the formula were L[i,i] = - sum(L[i, :]) we would require that L[i,i] = 0. However, because the assignment subtracts off the entire row sum, it also subtracts any erroneous part calculated for L[i,i] initially. The existence of the zero-eigenvalue mode supports this.

**Comment by thomasscaffidi** [comment]
You're right sorry I did not see it was -= and not = -
