### ISSUE TITLE
η not defined here?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#2]
https://github.com/DavisThuillier/Ludwig.jl/blob/983ea415143ce77f9859ec0f940c28f5f52eb831/src/integration.jl#L42

I could not find where η is defined in this function. 
Also, it is defined in ee_kernel with a different convention (Delta Epsilon / 2 already included in eta), so that might cause confusion.

**Comment by DavisThuillier** [comment]
Old version of function scrubbed from integration.jl
