### ISSUE TITLE
The inverse determinant should be taken in absolute value?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#3]
https://github.com/DavisThuillier/Ludwig.jl/blob/7c3265dc00dbe8bfe4208e97b7bd9b1867743f05/src/mesh/mesh.jl#L374

I think the factors of inverse det(J) coming from the change of volume in Eq 3.31 of Buhmann should be taken as absolute value

**Comment by thomasscaffidi** [comment]
On the other hand, the factors of inverse det(J) which show up in the definition of the inverse jacobian Eq 3.20 of Buhmann) should not be taken with an absolute value

**Comment by DavisThuillier** [comment]
Absolute value enforced now in mesh.jl
