### ISSUE TITLE
Proposal to remove possible issue with zero mode in phi

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#5]
https://github.com/DavisThuillier/Ludwig.jl/blob/e12cc78de30933ce5456febaf2c79c125132d167/src/properties.jl#L35

I propose to use instead
η = prefactor * 0.25 * inner_product(Dxx .- Dyy, Dxx .- Dyy, L, fd .* (1 .- fd) .* dV)
because this ensures the components proportional to the density zero mode drops out completely.

Otherwise, the bisgstab-calculated phi could in general have a non-zero component along the zero mode, which would then give a non-zero contribution when contracting it with Dxx alone.

**Comment by DavisThuillier** [comment]
Good idea! Changed.
