### ISSUE TITLE
Missing t5 term in deformation potential for alpha/beta ?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#7]
https://github.com/DavisThuillier/Ludwig.jl/blob/e12cc78de30933ce5456febaf2c79c125132d167/scripts/materials/Sr2RuO4.jl#L65

**Comment by DavisThuillier** [comment]
Including the t5 term causes bizarre cusps at integer multiples of pi/2. Unsure of how to resolve.

**Comment by DavisThuillier** [comment]
Issue identified: the derivative of V must needs be preceded by a factor of V itself giving us an overall t5^2 scaling. The extra factor of sign(V) takes care of the cusps.
