### ISSUE TITLE
Why add the \Delta \epsilon in quadrature?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#8]
https://github.com/DavisThuillier/Ludwig.jl/blob/ae410e2cd2960b22efeb5ac8ca592a9f3aa514e0/src/integration.jl#L162

Based on this formula, it seems you would get a factor of sqrt(2) in front of the actual \Delta \epsilon you want to use for the formula for Iab (3.45 of Buhmann).

**Comment by DavisThuillier** [comment]
Error fixed.
