### ISSUE TITLE
Not clear what this line does?

### ISSUE THREAD

**Issue by thomasscaffidi** [DavisThuillier/Ludwig.jl#9]
https://github.com/DavisThuillier/Ludwig.jl/blob/ae410e2cd2960b22efeb5ac8ca592a9f3aa514e0/scripts/electron_impurity.jl#L26

**Comment by DavisThuillier** [comment]
This line was previously used when the band weight for impurity scattering was uniform. Deprecated and now removed. Did not affect functionality, since V_squared is redefined as a matrix in line 28.
